server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml

logging:
  level:
    org.springframework.web: DEBUG